# Generated by Django 5.1.7 on 2025-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.IntegerField()),
                ('organismo', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=20)),
                ('caratula', models.CharField(max_length=150)),
                ('fechaultmov', models.DateField()),
            ],
        ),
    ]
