# Generated by Django 5.1.7 on 2025-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='exp_id',
            field=models.IntegerField(max_length=80),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fechaultmov',
            field=models.CharField(max_length=150),
        ),
    ]
