# Generated by Django 5.1.7 on 2025-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expediente', '0002_alter_expediente_exp_id_alter_expediente_fechaultmov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='exp_id',
            field=models.CharField(max_length=150),
        ),
    ]
